In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
print("Type of array is : ",arr1.dtype)

Type of array is :  int32


In [26]:
print("Shape of array is : ",arr1.shape)

Shape of array is :  (10,)


In [25]:
print("Size of the arary is : ",arr1.size)

Size of the arary is :  10


In [24]:
print("Dimension of array is : ",arr1.ndim)

Dimension of array is :  1


In [27]:
print("Length of array is : ",len(arr1))

Length of array is :  10


In [28]:
print("Reversed array : ",arr1[::-1])

Reversed array :  [10  9  8  7  6  5  4  3  2  1]


In [29]:
print("Sliced array : ",arr1[2:8])

Sliced array :  [3 4 5 6 7 8]


In [30]:
print("Elements greater than 5 in array :",arr1[arr1>5])

Elements greater than 5 in array : [ 6  7  8  9 10]


In [33]:
arr=np.array([[3,1,4],[4,2,9],[10,6,2],[11,2,5]])
print("Origial array is : ",arr)

Origial array is :  [[ 3  1  4]
 [ 4  2  9]
 [10  6  2]
 [11  2  5]]


In [36]:
print(" \n Reshaped array is :\n ",arr.reshape(4,3))

 
 Reshaped array is :
  [[ 3  1  4]
 [ 4  2  9]
 [10  6  2]
 [11  2  5]]


In [41]:
print(" \n Sorted array is : \n",np.sort(arr))

 
 Sorted array is : 
 [[ 1  3  4]
 [ 2  4  9]
 [ 2  6 10]
 [ 2  5 11]]


In [42]:
print(" \n Sliced array is : \n",arr[2:6])

 
 Sliced array is : 
 [[ 2  6 10]
 [ 2  5 11]]


In [43]:
print(" \n Extracted 1st Column : \n",arr[:,0])

 
 Extracted rows : 
 [1 2 2 2]


In [45]:
print("\n Extracted 1st row : \n",arr[0,:])


 Extracted 1st row : 
 [1 3 4]
