In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
s=arr[2:6]
print(s)

[3 4 5 6]


In [24]:
m=arr[::2]
print(m)

[1 3 5 7 9]


In [26]:
n=arr[::-1]
print(n)

[9 8 7 6 5 4 3 2 1]


In [36]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar[0:2,1:3])

[[2 3]
 [5 6]]


In [45]:
print(ar[:,0])
print(ar[1,:])

[1 4 7]
[4 5 6]


In [49]:
print(ar[0,0],ar[1,2])

1 6


In [61]:
ary=np.array([10,20,30,40,50])
print(ary[1])
print(ary[-1])
print(ary[1:4])

20
50
[20 30 40]


In [65]:
print(ary[ary>25])

[30 40 50]


In [71]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(np.hstack((arr1,arr2))) # joins horizontaly
print("\n")
print(np.vstack((arr1,arr2))) # join vertically 
print("\n")
print(np.dstack((arr1,arr2))) # join in depth wise level

[[1 2 5 6]
 [3 4 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [81]:
print(np.array_split(arr,4))

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [4]:
m=np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(m,4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]
